  - name: installs the nova compute component of openstock
    shell:
      sudo apt install nova-compute -y

  - name: installs the openstock client
    shell:
      sudo apt install python3-openstackclient -y
